"""Parse the two client menu files into a TypeScript dish-seed module.

  - "New Room Service Menu Updated.xlsx" → SERVICE menu (room service /
    à la carte / management). Per-dish price + serving window.
  - "DOC-20260306-WA0037..docx" → BANQUET menu (banquet / ODC / packet).
    No prices — package-priced, so unitPrice 0.

A dish appearing in BOTH menus is emitted once with menu="BOTH" and the
SERVICE price (so it stays orderable à la carte). Each dish gets a stable
code (SVC-#### / BNQ-#### / BOTH-####) so the seed can upsert idempotently.

Writes prisma/seed-data/dishes.ts.
"""
import json
import re
import openpyxl
from docx import Document


def ts(s):
    if s is None:
        return "null"
    return json.dumps(s, ensure_ascii=False)


def clean(s):
    return s.replace("�", "-").replace("  ", " ").strip().strip("-").strip()


def parse_service():
    wb = openpyxl.load_workbook(
        "H:/Cater/Catering/New Room Service Menu Updated.xlsx",
        data_only=True,
        read_only=True,
    )
    ws = wb["Sheet1"]
    rows = list(ws.iter_rows(values_only=True))
    section = None
    out = []
    seen = set()
    for r in rows:
        c0 = str(r[0]).strip() if r and r[0] else ""
        c1 = str(r[1]).strip() if r and len(r) > 1 and r[1] else ""
        c2 = str(r[2]).strip() if r and len(r) > 2 and r[2] else ""
        if not c0 or c0.upper() == "MENU":
            continue
        if c1 == "Price" or not c1:
            section = c0
            continue
        try:
            price = float(c1)
        except ValueError:
            continue
        name = clean(c0)
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(
            {
                "name": name,
                "category": section or "Misc",
                "unitPrice": price,
                "timing": c2 or None,
            }
        )
    return out


def parse_banquet():
    doc = Document("H:/Cater/Catering/DOC-20260306-WA0037..docx")
    out = []
    seen = set()
    section = "Banquet"
    for p in doc.paragraphs:
        t = p.text.strip()
        if not t:
            continue
        up = t.upper()
        if up == "BANQUET MENU" or re.search(r"ANY\s*\d", up):
            section = clean(re.sub(r"[\(\-–].*$", "", t)).strip() or section
            continue
        for part in re.split(r"\s{3,}", t):
            name = clean(part)
            if not name or len(name) < 2:
                continue
            key = name.lower()
            if key in seen:
                continue
            seen.add(key)
            disp = name if not name.isupper() else name.title()
            out.append({"name": disp, "category": section})
    return out


def build():
    service = parse_service()
    banquet = parse_banquet()

    svc_by_key = {d["name"].lower(): d for d in service}
    bnq_by_key = {d["name"].lower(): d for d in banquet}
    both_keys = set(svc_by_key) & set(bnq_by_key)

    records = []
    svc_n = bnq_n = both_n = 0

    # SERVICE-only + BOTH
    for d in service:
        key = d["name"].lower()
        desc = f"Served {d['timing']}" if d["timing"] else None
        if key in both_keys:
            both_n += 1
            code = f"BOTH-{both_n:04d}"
            menu = "BOTH"
        else:
            svc_n += 1
            code = f"SVC-{svc_n:04d}"
            menu = "SERVICE"
        records.append(
            {
                "code": code,
                "name": d["name"],
                "category": d["category"],
                "menu": menu,
                "unitPrice": d["unitPrice"],
                "description": desc,
            }
        )

    # BANQUET-only (skip names already emitted as BOTH)
    emitted = {r["name"].lower() for r in records}
    for d in banquet:
        key = d["name"].lower()
        if key in emitted:
            continue
        bnq_n += 1
        records.append(
            {
                "code": f"BNQ-{bnq_n:04d}",
                "name": d["name"],
                "category": d["category"],
                "menu": "BANQUET",
                "unitPrice": 0,
                "description": None,
            }
        )

    return records, svc_n, bnq_n, both_n


def main():
    records, svc_n, bnq_n, both_n = build()
    lines = []
    lines.append("// AUTO-GENERATED by scripts/parse-dishes.py — do not edit by hand.")
    lines.append("// Source: client's room-service Excel + banquet DOCX.")
    lines.append(f"// {len(records)} dishes "
                 f"({svc_n} service-only, {bnq_n} banquet-only, {both_n} in both).")
    lines.append("")
    lines.append('import type { DishMenu } from "@prisma/client";')
    lines.append("")
    lines.append("export interface DishSeed {")
    lines.append("  code: string;")
    lines.append("  name: string;")
    lines.append("  category: string;")
    lines.append("  menu: DishMenu;")
    lines.append("  unitPrice: number;")
    lines.append("  description: string | null;")
    lines.append("}")
    lines.append("")
    lines.append("export const dishSeed: DishSeed[] = [")
    for r in records:
        lines.append(
            "  {{ code: {c}, name: {n}, category: {cat}, menu: {m}, unitPrice: {p}, description: {d} }},".format(
                c=ts(r["code"]),
                n=ts(r["name"]),
                cat=ts(r["category"]),
                m=ts(r["menu"]),
                p=r["unitPrice"],
                d=ts(r["description"]),
            )
        )
    lines.append("];")
    lines.append("")

    out_path = "indefine-kitchen/prisma/seed-data/dishes.ts"
    import os
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_path}: {len(records)} dishes "
          f"({svc_n} service, {bnq_n} banquet, {both_n} both)")


if __name__ == "__main__":
    main()
