"""Parse the client's store files into a TypeScript seed module:
  - Maintainance Materials.xlsx  -> MaintenanceItem rows
  - Store Inventory On Daily Basis.xlsx -> Ingredient rows (kitchen store)
  - HK requirement list (typed inline) -> HousekeepingItem rows

Writes prisma/seed-data/stores.ts. Idempotent keys:
  Ingredient    -> sku  (STR-####)
  MaintenanceItem / HousekeepingItem -> name (both @@unique on name)
"""
import json
import re
import os
import openpyxl


def ts(s):
    return json.dumps(s, ensure_ascii=False) if s is not None else "null"


def num(x, places=3):
    try:
        return round(float(x), places)
    except (TypeError, ValueError):
        return 0


# Maintenance items that are plumbing/mechanical, not electrical.
GENERAL_HINTS = ("water tape", "spray gun", "shower", "pipe")


def parse_maintenance():
    wb = openpyxl.load_workbook(
        "H:/Cater/Catering/Maintainance Materials.xlsx",
        data_only=True, read_only=True,
    )
    ws = wb["Sheet1"]
    out, seen = [], set()
    for r in ws.iter_rows(values_only=True):
        if not r or not r[0] or not str(r[0]).strip().isdigit():
            continue
        if len(r) < 2 or not r[1]:
            continue
        name = re.sub(r"\s+", " ", str(r[1]).strip())
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        cat = "GENERAL" if any(h in key for h in GENERAL_HINTS) else "ELECTRICAL"
        out.append({"name": name, "category": cat, "unit": "piece"})
    return out


def parse_ingredients():
    wb = openpyxl.load_workbook(
        "H:/Cater/Catering/Store Inventory On Daily Basis.xlsx",
        data_only=True, read_only=True,
    )
    ws = wb["Sheet1"]
    rows = list(ws.iter_rows(values_only=True))
    out, seen = [], set()
    n = 0
    for r in rows[2:]:
        if not r or r[1] is None or not str(r[1]).strip():
            continue
        name = re.sub(r"\s+", " ", str(r[1]).strip())
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        n += 1
        unit = str(r[3]).strip() if len(r) > 3 and r[3] else "kg"
        inv = num(r[2]) if len(r) > 2 else 0
        rate = num(r[4], 4) if len(r) > 4 else 0
        out.append(
            {
                "sku": f"STR-{n:04d}",
                "name": name,
                "unit": unit,
                "openingQty": inv,
                "openingAvgCost": rate,
            }
        )
    return out


# 34 HK items from the client's HK Requirement sheet (typos corrected).
HK_ITEMS = [
    ("Milk Powder", "Pantry", "pkt"),
    ("Assam Tea", "Pantry", "box"),
    ("Sugar Free", "Pantry", "box"),
    ("Hand Gloves", "Hygiene", "box"),
    ("Mask", "Hygiene", "piece"),
    ("Stirrer Stick", "Pantry", "box"),
    ("Sugar", "Pantry", "pkt"),
    ("Dental Kit", "Amenities", "piece"),
    ("Soap", "Amenities", "piece"),
    ("R-9 Cleaning Chemical", "Chemicals", "ltr"),
    ("R-3 Cleaning Chemical", "Chemicals", "ltr"),
    ("R-2 Cleaning Chemical", "Chemicals", "ltr"),
    ("R-6 Cleaning Chemical", "Chemicals", "ltr"),
    ("R-5 Cleaning Chemical", "Chemicals", "ltr"),
    ("Room Freshener Lemongrass Oil", "Chemicals", "ltr"),
    ("Laundry Bag", "Amenities", "piece"),
    ("Soap Oil", "Chemicals", "ltr"),
    ("Dish Wash", "Chemicals", "ltr"),
    ("Shaving Kit", "Amenities", "piece"),
    ("Hair Wash", "Amenities", "piece"),
    ("Body Wash", "Amenities", "piece"),
    ("Dry Mop Set", "Cleaning Tools", "set"),
    ("Comb", "Amenities", "piece"),
    ("Green Scrubber", "Cleaning Tools", "piece"),
    ("Tissue Roll", "Amenities", "box"),
    ("Micro Fiber Dusting Cloth", "Cleaning Tools", "piece"),
    ("Dusting Cloth Red", "Cleaning Tools", "piece"),
    ("Green Tea", "Pantry", "box"),
    ("Lemon Tea", "Pantry", "box"),
    ("M Fold Tissue", "Amenities", "box"),
    ("Pickup Box", "Cleaning Tools", "piece"),
    ("Roof T16 Chemical", "Chemicals", "ltr"),
    ("Salt & Pepper", "Pantry", "piece"),
    ("Coconut Oil", "Amenities", "ltr"),
]


def emit():
    maint = parse_maintenance()
    ings = parse_ingredients()
    hk = HK_ITEMS

    lines = []
    A = lines.append
    A("// AUTO-GENERATED by scripts/parse-stores.py — do not edit by hand.")
    A("// Sources: Maintainance Materials.xlsx, Store Inventory On Daily")
    A("// Basis.xlsx, and the client's HK Requirement sheet.")
    A(f"// {len(maint)} maintenance, {len(ings)} ingredients, {len(hk)} housekeeping.")
    A("")
    A("export interface MaintItemSeed { name: string; category: string; unit: string }")
    A("export interface IngredientSeed { sku: string; name: string; unit: string; openingQty: number; openingAvgCost: number }")
    A("export interface HkItemSeed { name: string; category: string; unit: string }")
    A("")
    A("export const maintenanceItemSeed: MaintItemSeed[] = [")
    for m in maint:
        A(f'  {{ name: {ts(m["name"])}, category: {ts(m["category"])}, unit: {ts(m["unit"])} }},')
    A("];")
    A("")
    A("export const ingredientSeed: IngredientSeed[] = [")
    for i in ings:
        A(f'  {{ sku: {ts(i["sku"])}, name: {ts(i["name"])}, unit: {ts(i["unit"])}, openingQty: {i["openingQty"]}, openingAvgCost: {i["openingAvgCost"]} }},')
    A("];")
    A("")
    A("export const housekeepingItemSeed: HkItemSeed[] = [")
    for h in hk:
        A(f'  {{ name: {ts(h[0])}, category: {ts(h[1])}, unit: {ts(h[2])} }},')
    A("];")
    A("")

    out_path = "indefine-kitchen/prisma/seed-data/stores.ts"
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_path}: {len(maint)} maint, {len(ings)} ingredients, {len(hk)} hk")


if __name__ == "__main__":
    emit()
